### ISSUE TITLE
Use sddm instead of lightdm

### ISSUE THREAD

**Issue by jeremy447** [Antergos/antergos-kde-setup#10]
Hello,

As the title says, it should be better to use sddm instead of lightdm with the KDE/Plasma desktop. It already have been discussed here a little bit https://github.com/Antergos/antergos-packages/issues/95 but without any change for now. I understand that to achieve the same look on all desktop using the same dm make sense but it's not really optimal and having the same look for the dm is not really important at the end because the desktops don't look the same ! Using the recommended dm of each desktop make more sense even if the look won't be the same. Furthermore lightdm with the lightdm-webkit2-greeter is utterly slow. It's already have been [discussed](https://forum.antergos.com/topic/3082/the-login-screen-for-antergos-is-incredibly-slow) but there is no fix for now.

Thanks !

**Comment by lots0logs** [comment]
Sorry this is a non-starter. We want all desktops to have a consistent experience after installation. We do appreciate your interest and efforts though! :smiley:
