### ISSUE TITLE
Monitor doesn't wake up after turning off by Plasma energy management

### ISSUE THREAD

**Issue by piomiq** [Antergos/antergos-kde-setup#11]
Hi

I have up-to-date Angergos, so on today this is:
Plasma 5.8.3 and xf86-video-intel 1:2.99.917+722+g714052f-1 and kernel 4.8.6-ARCH

On my desktop I have set "Safe screen energy" with "Switch off after" 15 min. And when this time expires, monitor goes sleep, so turn off. Great. Unfortunately I'm not able to wake up it. Moving, clicking by mouse doesn't help. The same for keyboard. Also switching to text console doesn't help. Monitor is still turned off. I don't know where the guilty lies. I observe this issue starting Plasma 5.8.2 (also I met it in KaOS on my laptop with Intel HD graphics), but till current update (Plasma 5.8.3) also Intel graphics driver was updated several times.

The workaround is disable turning off the monitor. To restore monitor from turning off mode is blind login no text terminal and killing lightdm or restart the system. This is very annoying issue.

My hardware is following Skylake Intel i7-6700, and graphics HD 530 (GT2)
Laptop is working with Sandy Bridge Intel i5, also with the newest intel graphics drivers.

**Comment by karasu** [comment]
Could you try using sddm instead of lightdm?

**Comment by lots0logs** [comment]
@karasu I doubt this has anything to do with lightdm to be honest. Sounds like a bug in Plasma to me. IJS

**Comment by karasu** [comment]
I just thought that maybe Plasma relayed on sddm on this one.

**Comment by lots0logs** [comment]
I doubt it. So many people think SDDM is a KDE project but the reality is that its not. It never was and it still isn't. It's a desktop agnostic DM just like LightDM. It does have close ties with the QT toolkit for its themes (which use QML) though.

**Comment by karasu** [comment]
Learn something new every day! :grimacing:

**Comment by lots0logs** [comment]
Hey, any day you learn something new is a good day IMO :triumph:

**Comment by piomiq** [comment]
And maybe this issue is related with the newest Intel drivers?
I don't remember if this happened me in September or begin of October.
Anyway I will report bug in bugs.kde.org/

**Comment by piomiq** [comment]
I retested this issue again with last updates (Intel drivers and kernel) and seems that now it works fine. 
Monitor wakes up after moving mouse.
Retested with:
  Plasma 5.8.3
  1:2.99.917+730+gdad64e9-1
  kernel 4.8.8-ARCH

(time after monitor was turned off in this test was: 2 min.)
