### ISSUE TITLE
XRandR/Plasma detects not existing display

### ISSUE THREAD

**Issue by piomiq** [Antergos/antergos-kde-setup#13]
After last updates for Frameworks 5.27.0 and intel video driver (version mentioned below) I met very annoying issue. My configuration of monitor extended with new not existing monitor called "laptop monitor" (code in configuration eDP1). I work on desktop and I didn't connect any devices to my motherboard (by HDMI or other socket).

Wasn't be so bad only this monitor broke my desktop. All opened windows went to this desktop. I had to drag them (blindly) to main desktop by Alt+hold left button of mouse (BTW. Thanks for this great option). Some new windows still opens on this not visible desktop (for example mplayer). I have installed desktop pager plasmoid and it thinks that some additional display devices is connected, because it's shape is a bit flatten, the same I could connect something by HDMI to my laptop.

I tried to remove the entry describing new not existing display from configuration file placed in ~/.local/share/kscreen directory. For this purpose I logged off, switched to text terminal and removed entry from this file and also removed row "eDP1" from file ~/.config/plasmashellrc in section:
[ScreenConnectors]
0=DP1
1=eDP1

After reboot (run in terminal) and login again to plasma and unwanted entry back, so also not existing display. When I try to switch off this display in systemsetting then my monitor turns off.

I'm not sure if this is issue made by new intel driver or kscreen.

Software:
  Plasma 5.8.3  (kscreen 3.8.3)
  xf86-video-intel 1:2.99.917+730+gdad64e9-1
  kernel 4.8.8-ARCH
Hardware:
  Skylake Intel i7-6700 and graphics HD 530 (GT2)

**Comment by piomiq** [comment]
I found/discovered some workaround or a fix.
When I switched off unwanted deisplay in System Settings my monitor turns off then I restarted X (Alt+Ctrl+Backspace), I switched to text terminal and manually enabled (in kscreen configuration file) not existing display. After login again to the plasma the issue magically fixed itself. I mean. Desktop pager plasmoid looks normal, mplayer shows window on current desktop. I can't move mouse cursor behind abroad of desktop. In System Settings I can see only one display.

Only one side effect is that my all desktop plasmoids disappeared :(. Probably they left on not visible display :-/.

**Comment by piomiq** [comment]
Only one side effect is that my desktop plasmoids disappeared :(. Probably all left on not visible display :-/.

**Comment by piomiq** [comment]
This is bug in last stable Plasma (ver. 5.8.3).
I reported this issue here: https://bugs.kde.org/show_bug.cgi?id=372557. Answered me Christoph Feck and said that this bug is fixed in next Plasma (ver. 5.8.4).
I suppose we have to wait for release it (maybe at December 1st, 2016) by KDE team, and availability in Antergos, after couple weeks :-/.

**Comment by karasu** [comment]
Thanks @piomiq for investigating this and posting here your results ;)

**Comment by piomiq** [comment]
Worth to note that this issue happens on desktop (on my side with mentioned hardware). I tested Plasma 5.8.3 on KaOS and OpenSUSE Tunbleweek using laptop (with Intel Sandy Bridge and Ivy Bridget) and this didn't happen.

I think would be nice when Arch/Antergos developers would prepare the fixed kscreen package from branch Plasma 5.8.4. Of course if this is possible. I don't want to break coherence of the system building kscreen from AUR, whereas this package will be provide in the future using normal channel only when Plasma 5.8.4 will be released.

**Comment by piomiq** [comment]
@karasu I'm not sure why you closed my issue when bug is not yet fixed in distribution?
Did you do this because, this is upstream issue?

**Comment by karasu** [comment]
Yes, if I understood correctly, 5.8.4 fixes the issue. As we use Arch repositories, we must wait until they update this package. You should complain about this to Arch packagers, but I doubt they will change their plans for this (I'm sure it's a matter of days, though).

**Comment by piomiq** [comment]
Even it could be the same version of kscreen (5.8.3) only with patch fixing mentioned issue.
As far as I know packagers release next version the same package increasing the number of build. I mean this number after minus on end of name the package, like in example: clementine-1.3.1-2 is second build with some patches, as I suppose. Maybe this would be possible?

I think Plasma is released every month, so if 5.8.3 was release at November 1st, then 5.8.4 will be released at Devember 1st. After that packages must be retested, so I suppose the soonest term when Plasma 5.8.4 will appear will be Dec 5th, so several weeks.

Whereas in this time in every run/restart of computer I need to clear ~/.cache, remove additional display name from ~/.config/plasmashellrc, and remove additional configuration of display from ~/.local/kscreen/fileconfig_with_generated_name. This is a bit annoying :-(

**Comment by piomiq** [comment]
Hmm. Plasma 5.8.4 release. I hope it will fill my issue.

**Comment by piomiq** [comment]
After update to new Plasma, restart computer I can say only that issue still persist.
I'm really unhappy from this :-(. I'm feeling like with beta software :-/.

Additionally adding any plasmoid works wrong, because after add it and try to move, it just disappears.
