### ISSUE TITLE
failed to update the package to version 1.02-2

### ISSUE THREAD

**Issue by cgw21** [Antergos/antergos-kde-setup#17]
Hello,

I am currently using yaourt -Syu to update my system and I keep running into a "failed to commit transaction (conflicting file)" after running the command. The issue seems to only be with antergos-kde-setup and the issue seems to be  the icon files. I have linked a screen shot of my terminal output for clarification. 
![image](https://user-images.githubusercontent.com/21348376/31248171-91112176-a9d8-11e7-8773-abd0fb45a2e0.png)

Any help would be appreciated
Thanks

**Comment by peterlerche** [comment]
Got exactly the same issue using pacman -Suy or Pamac GUI

**Comment by CaptainSwag101** [comment]
Same here, install failed due to existing files, seems to be mostly theme data causing the issue.

**Comment by hak8or** [comment]
Wanted to confirm I am also having this issue.

For anyone else stuck with this, doing ```yaourt -Syua --ignore antergos-kde-setup``` will let you upgrade your system while skipping this package.
