### ISSUE TITLE
antergos-kde-setup: removing kdenetwork-kopete breaks dependency 'kdenetwork-kopete'

### ISSUE THREAD

**Issue by piomiq** [Antergos/antergos-kde-setup#20]
Hi

I'm not able to update system (all packages on one time) by any tool (octopi, pamac), including in terminal by: "pacman -Syu". I'm able to update only single packages - one by one - which appeared in update. I mean by this way: 
```
$ sudo pacman -S package1_name package2_name ...
```
An error as I get is as following:

```
$ sudo pacman -Syu
[sudo] password for piotr: 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 antergos is up to date
:: Starting full system upgrade...
:: Replace kdenetwork-kopete with extra/kopete? [Y/n] Y
:: Replace kdeutils-sweeper with extra/sweeper? [Y/n] Y
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: antergos-kde-setup: removing kdenetwork-kopete breaks dependency 'kdenetwork-kopete'
:: antergos-kde-setup: removing kdeutils-sweeper breaks dependency 'kdeutils-sweeper'
```

**Comment by piomiq** [comment]
In system I have two packages with name kopete, so:
- kopete
- kdenetwork-kopete (installed from AUR)

I was trying to remove kdenetwork-kopete without success.
I checked files for both mentioned packages and they point to the same files.
So maybe a try of simple removing was finished with fail:
```
$ sudo pacman -R -d kdenetwork-kopete 
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: antergos-kde-setup: removing kdenetwork-kopete breaks dependency 'kdenetwork-kopete'
```
A try of removing entry in database. Used option: "--dbonly", which makes only: "Adds/removes the database entry only, leaving all files in place.". Doesn't finish with success :(.
```
$ sudo pacman -R --dbonly kdenetwork-kopete 
[sudo] password for piotr: 
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: antergos-kde-setup: removing kdenetwork-kopete breaks dependency 'kdenetwork-kopete'
```

Do you have any suggestions how to remove kdenetwork-kopete or fix issue mentioned in title?

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/issues/266

Cheers!
