### ISSUE TITLE
Default KDE installation greeter (lightdm?) appears to be software accelerated despite nvidia-340xx-libgl et al. being installed?

### ISSUE THREAD

**Issue by ermo** [Antergos/antergos-kde-setup#4]
During graphical login using the default KDE installation greeter, the animations and indeed the general screen response times are so slow that it tends to suggest that software emulation is being used? Is this per design?

Once logged in, the KDE Plasma Desktop is clearly hardware accelerated (Nvidia 8800GT using 340xx drivers).

```
$ pacman -Q |grep lightdm
lightdm 1:1.18.1-1
lightdm-webkit2-greeter 2.1.3-1
$ pacman -Q |grep nvidia
nvidia-340xx-dkms 340.96-10
nvidia-340xx-libgl 340.96-1
nvidia-340xx-utils 340.96-1
$ lspci -k | grep -A 2 -E "(VGA|3D)"
01:00.0 VGA compatible controller: NVIDIA Corporation G92 [GeForce 8800 GT] (rev a2)
        Subsystem: NVIDIA Corporation Device 053c
        Kernel driver in use: nvidia
$ glxinfo | grep direct
direct rendering: Yes
```

(see issue #3 for my xorg log)

**Comment by ghost** [comment]
sucks doesnt it....
more to the point...i still dont know why sddm wasnt the default display manager...
u can just install sddm and sddm-kcm packages....and then disable lightdm and enable sddm

**Comment by lots0logs** [comment]
@ermo The problem causing lag on some systems was fixed upstream. Please let me know if you still experience the problem on your fully up-to-date system (`sudo pacman -Syyu`)

**Comment by lots0logs** [comment]
Issue moved to [Antergos/lightdm-webkit2-greeter #89](https://github.com/Antergos/lightdm-webkit2-greeter/issues/89) via [**ZenHub**](https://www.zenhub.com/)
