### ISSUE TITLE
Make some softs optionnal

### ISSUE THREAD

**Issue by jeremy447** [Antergos/antergos-kde-setup#9]
Hello,

I don't use and don't need these softs `kdeutils-sweeper kcalc clementine vlc` but if I try to remove them pacman says that it will break `antergos-kde-setup`.

`antergos-kde-setup` should let us remove non critical softs.

Thanks !

**Comment by lots0logs** [comment]
The purpose of the `antergos-kde-setup` package is to install and configure the default antergos configuration for KDE. It is not necessary for you to keep the package installed going forward. You can remove it and any of its dependencies at any time.

**Comment by jeremy447** [comment]
Ok thank you !

**Comment by lots0logs** [comment]
You're welcome! Thanks for taking the time to send us your feedback/concerns :smiley:
